dist: trusty
language: java
jdk:
    - oraclejdk8


sudo: required

before_install:
# Install Thrift
    - sudo apt-get update -qq
    - sudo apt-get install -y --no-install-recommends automake bison curl flex g++ libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-system-dev libboost-test-dev libevent-dev libssl-dev libtool make pkg-config
#    - wget https://archive.apache.org/dist/thrift/0.11.0/thrift-0.11.0.tar.gz
#    - tar xfz thrift-0.11.0.tar.gz
#    - cd thrift-0.11.0
#    - ./configure --without-go --without-php --without-python --without-ruby --without-cpp --without-js --without-node --without-erlang --without-c_glib
#    - sudo make install
#    - cd ..
    - sudo apt-get install -y thrift-compiler
addons:
    sonarcloud:
        organization: "tonydeng-github"
        token:
            secure: "DulBUc3HihVEXHZLvniZ92jM3yQBVkUXHLWp6nBgQpeu/GkKiH7NvHovbl3rmev16xYBC5T6wukMcGP7Mzdzr4kjqFDvxJlFvKMnp1Aa+iCkow5LHnmeMx4/SOrzJjCJxICrTPmplwKJNSDgv4+5Be9xQ7xuCfqdaV2b7N7i4N8o5JhiKh6pEWS2pgmsf9T03jYo2v7Mg54ifO4OMR7u45cYyL2lNSYQZsasuQxZHvVndaYMZSRoiyw2TsXlp31R4Ew0MWg+QPT9UIadmi4sOZKMhdv07s8k+lw2Uj1K/p1Pqtq9QAMkynl9Tto51qgoDYQydwYc9HNupRffDlHrURQkr8GGHppl3lpL4lgC7nxGxYPC2GpqO5D/wBBxFP4LhgtIH6iX/N7nDE8v0QYLG9tuyknxsw7TgvgiKAvMbUhugYzc3njsRiDOAT5yzA96z/DoOOgIanwe99e2dCAWxFIaHbzj16bCI6nP0YKqZd5kTTSaESLiGmgJINLR0gmK8WANv5hGOGhyO31aksx2SfrgpC/sQtvvRH7fTfP1Tpt3wfQE35KxToDZdJnX4NnqB5wwOt6cJYRhYsYpGBqEjCDJZnj+B43JN5Yq7sLmz2sEoUkgjC1B7ciBcidHcMw4ZzH0uNYRk68QvkBPmZS9NIt7+8N6KE4dE+Ng61rFO8A="

script:
    # JaCoCo is used to have code coverage, the agent has to be activated
    - mvn install -T20
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.sonar/cache'