dist: trusty
language: java
jdk:
    - oraclejdk8


sudo: required

before_install:
# Install Thrift
    - sudo apt-get update -qq
    - sudo apt-get install -y --no-install-recommends automake bison curl flex g++ libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-system-dev libboost-test-dev libevent-dev libssl-dev libtool make pkg-config
#    - wget https://archive.apache.org/dist/thrift/0.11.0/thrift-0.11.0.tar.gz
#    - tar xfz thrift-0.11.0.tar.gz
#    - cd thrift-0.11.0
#    - ./configure --without-go --without-php --without-python --without-ruby --without-cpp --without-js --without-node --without-erlang --without-c_glib
#    - sudo make install
#    - cd ..
    - sudo apt-get install -y thrift-compiler

script:
    # JaCoCo is used to have code coverage, the agent has to be activated
    - mvn install -T20
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.sonar/cache'